### ISSUE TITLE
Revamp To-Do

### ISSUE THREAD

**Issue by robbiejaeger** [turingschool/front-end-curriculum#360]
* [ ] Landing page: remove unnecessary links and add hero image (in PR)
* [ ] Landing page: after unnecessary links are removed, add small sections for remaining information (paired.tech, mentor list?, professional development, mod-0 capstone?)
* [ ] Add styling for specific sections: turn and talk, on your own (you do), CFUs, homework, pro-tip (side notes)
* [ ] Add line numbers to code snippets
* [ ] Consistent image styling and sizing (centered, not giant)
* [ ] Embedding typeform surveys for CFUs?

**Comment by robbiejaeger** [comment]
Made separate issues for each of these. Closing.
